---
name: pre-commit

on:
  pull_request:
    branches: ['**']
  push:
    branches: [stage, main]

jobs:
  pre-commit:
    runs-on: ubuntu-latest
    timeout-minutes: 5
    steps:
    - uses: actions/checkout@v5
    - uses: actions/setup-python@v5
      with:
        python-version: '3.x'
    - uses: pre-commit/action@v3.0.1
      name: Validate renovate5.json
      with:
        extra_args: --all-files --verbose
    - name: Prepare for pre-commit
      run: |
        cp default.json5 .github/renovate.json5  # renovate-config-validator hook can only validate files that are called renovate.json5
        git add .github/renovate.json5
    - uses: pre-commit/action@v3.0.1
      name: Validate default5.json
      with:
        extra_args: --all-files --verbose
